[2024-11-16T21:46:25.595+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-16T21:46:25.618+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: criar_tabelas.create_table_query_summarydw manual__2024-11-16T21:45:07.450193+00:00 [queued]>
[2024-11-16T21:46:25.628+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: criar_tabelas.create_table_query_summarydw manual__2024-11-16T21:45:07.450193+00:00 [queued]>
[2024-11-16T21:46:25.628+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 2
[2024-11-16T21:46:25.643+0000] {taskinstance.py:2889} INFO - Executing <Task(PostgresOperator): create_table_query_summarydw> on 2024-11-16 21:45:07.450193+00:00
[2024-11-16T21:46:25.656+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=144) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-16T21:46:25.658+0000] {standard_task_runner.py:72} INFO - Started process 146 to run task
[2024-11-16T21:46:25.659+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'criar_tabelas', 'create_table_query_summarydw', 'manual__2024-11-16T21:45:07.450193+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmpdf9yzrd4']
[2024-11-16T21:46:25.660+0000] {standard_task_runner.py:105} INFO - Job 14: Subtask create_table_query_summarydw
[2024-11-16T21:46:25.717+0000] {task_command.py:467} INFO - Running <TaskInstance: criar_tabelas.create_table_query_summarydw manual__2024-11-16T21:45:07.450193+00:00 [running]> on host 7766afd0bc11
[2024-11-16T21:46:26.055+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='criar_tabelas' AIRFLOW_CTX_TASK_ID='create_table_query_summarydw' AIRFLOW_CTX_EXECUTION_DATE='2024-11-16T21:45:07.450193+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-16T21:45:07.450193+00:00'
[2024-11-16T21:46:26.055+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-16T21:46:26.056+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-16T21:46:26.056+0000] {logging_mixin.py:190} INFO - Current task name:create_table_query_summarydw state:running start_date:2024-11-16 21:46:25.618381+00:00
[2024-11-16T21:46:26.056+0000] {logging_mixin.py:190} INFO - Dag name:criar_tabelas and current dag run status:running
[2024-11-16T21:46:26.056+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-16T21:46:26.057+0000] {sql.py:278} INFO - Executing: 
CREATE TABLE IF NOT EXISTS dw.SummaryProfile (
    id INT PRIMARY KEY,
    address1 VARCHAR(255),
    address2 VARCHAR(255),
    city VARCHAR(100),
    state VARCHAR(2),
    zip VARCHAR(10),
    country VARCHAR(100),
    website VARCHAR(255),
    industry VARCHAR(100),
    industryKey VARCHAR(50),
    industryDisp VARCHAR(100),
    sector VARCHAR(100),
    sectorKey VARCHAR(50),
    sectorDisp VARCHAR(100),
    longBusinessSummary TEXT
);
[2024-11-16T21:46:26.067+0000] {base.py:84} INFO - Retrieving connection 'postgres-***'
[2024-11-16T21:46:26.091+0000] {base.py:84} INFO - Retrieving connection 'postgres-***'
[2024-11-16T21:46:26.098+0000] {sql.py:544} INFO - Running statement: 
CREATE TABLE IF NOT EXISTS dw.SummaryProfile (
    id INT PRIMARY KEY,
    address1 VARCHAR(255),
    address2 VARCHAR(255),
    city VARCHAR(100),
    state VARCHAR(2),
    zip VARCHAR(10),
    country VARCHAR(100),
    website VARCHAR(255),
    industry VARCHAR(100),
    industryKey VARCHAR(50),
    industryDisp VARCHAR(100),
    sector VARCHAR(100),
    sectorKey VARCHAR(50),
    sectorDisp VARCHAR(100),
    longBusinessSummary TEXT
);, parameters: None
[2024-11-16T21:46:26.099+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 284, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 489, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 549, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.InvalidSchemaName: schema "dw" does not exist
LINE 2: CREATE TABLE IF NOT EXISTS dw.SummaryProfile (
                                   ^

[2024-11-16T21:46:26.112+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-11-16T21:46:26.112+0000] {logging_mixin.py:190} INFO - Task start:2024-11-16 21:46:25.618381+00:00 end:2024-11-16 21:46:26.111568+00:00 duration:0.493187
[2024-11-16T21:46:26.112+0000] {logging_mixin.py:190} INFO - Task:<Task(PostgresOperator): create_table_query_summarydw> dag:<DAG: criar_tabelas> dagrun:<DagRun criar_tabelas @ 2024-11-16 21:45:07.450193+00:00: manual__2024-11-16T21:45:07.450193+00:00, state:running, queued_at: 2024-11-16 21:45:07.497426+00:00. externally triggered: True>
[2024-11-16T21:46:26.113+0000] {logging_mixin.py:190} INFO - Failure caused by schema "dw" does not exist
LINE 2: CREATE TABLE IF NOT EXISTS dw.SummaryProfile (
                                   ^
[2024-11-16T21:46:26.113+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=criar_tabelas, task_id=create_table_query_summarydw, run_id=manual__2024-11-16T21:45:07.450193+00:00, execution_date=20241116T214507, start_date=20241116T214625, end_date=20241116T214626
[2024-11-16T21:46:26.127+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-16T21:46:26.127+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 14 for task create_table_query_summarydw (schema "dw" does not exist
LINE 2: CREATE TABLE IF NOT EXISTS dw.SummaryProfile (
                                   ^
; 146)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 284, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 489, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 549, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.InvalidSchemaName: schema "dw" does not exist
LINE 2: CREATE TABLE IF NOT EXISTS dw.SummaryProfile (
                                   ^

[2024-11-16T21:46:26.194+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-16T21:46:26.223+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-16T21:46:26.227+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
